### ISSUE TITLE
[ENS DApp] Prevent name capitalization

### ISSUE THREAD

**Issue by jeluard** [status-im/contracts#16] opened 2018-08-10 16:07 UTC
On iOS at least, the name is automatically capitalized. This is an issue as most users won't notice this and fail to use their name.

**Comment by bgits** [comment] 2018-08-11 10:42
Resolved in this build: https://ipfs.infura.io/ipfs/QmW2Jx22kshyoqGtNrmhU7q54ore3X9P3Gbbocr5eJ29pT/

**Comment by jeluard** [comment] 2018-08-11 13:21
Nice! Do you mind adding link to commits to keep track of the root issue? Or maybe just using `Fixes #XXX` in the commit name to automatically close issues?

**Comment by jeluard** [comment] 2018-08-11 13:53
Still can reproduce with latest issue.

**Comment by bgits** [comment] 2018-08-11 14:25
How can I reproduce the issue?

**Comment by bgits** [comment] 2018-08-11 15:23
Here is the commit:

https://github.com/status-im/contracts/commit/c74c0a1682cd8dd82dfc9b0090ee7bb9b5ab7340

**Comment by jeluard** [comment] 2018-08-11 16:23
On iOs when you type a username in the input search it is automatically capitalized.
Maybe you could try the following: https://stackoverflow.com/questions/6356074/iphone-browser-defaulting-to-uppercase-for-first-letter-of-password-fields

**Comment by bgits** [comment] 2018-08-12 00:19
In this case that would not work because this is a controlled input. Here is the fix in this case:

https://github.com/status-im/contracts/commit/bd9d7b96df6a461249581e05466552eef666036e

**Comment by jeluard** [comment] 2018-08-12 09:29
Can you still capitalize some letters if you want to?

Also I am not sure controlled input would prevent using regular html attributes.

**Comment by bgits** [comment] 2018-08-12 10:51
In this solution you can not, we can make it more flexible to allow for that, but why since ENS names are case insensitive?

I tried using `autocapitalize="none"` with the controlled input on iOS and it does not work in this case, I can confirmed it works with an uncontrolled input.

**Comment by jeluard** [comment] 2018-08-12 14:47
Have you tried with `autoCapitalize` ? React uses the [camelCase](https://reactjs.org/docs/dom-elements.html) convention for attributes.

**Comment by bgits** [comment] 2018-08-13 11:36
I just tried it and it works, thanks! The interesting thing is `autocapitalize=none` works in react with a standard non controlled input.

https://github.com/status-im/contracts/commit/c8c23a8

**Closed as completed** 2018-08-13 15:45 UTC
